### PR TITLE
add PO prince5 data

### PR DESCRIPTION
**Pull request by clayton33**
Maybe before accepting the pull request, @casaultb , can you take a look at the file and see if there are any 'metadata' items that I'm missing to construct the cruise number format that you use. Maybe provide details how you construct the cruise number as a comment here, also include what components of COR2019001 is used to create the 18CO... cruise number.

Once this file gets the approval, I'll write code to convert necessary items such as cruise number and pressure to depth and any others to reduce issues for merging PO with BO data.

### CODE REVIEW

**Comment by casaultb** [comment]
I think the cruise number (descriptor) I am using (e.g. 18CO…) for the bio/chemical variables is the official cruise identifier adopted by dfo nationally. I think the other cruise number (e.g. COR2019…) is a cruise name assigned locally. I am attaching a couple of examples of cruise descriptors/names taken from Biochem to show the difference between the two. First column is the cruise name, second the cruise descriptor, third cruise leader, and fourth the start date. As you can see, there can be different names for a unique descriptor.

COR2019001      18OL19001         Cogswell, Andrew           07-APR-19
COR-2019-02 Baleine noire         18OL19001         ORTMANN, ALICE           07-AUG-19
IML-2019-09 Transects PMZA / Maquereaux       18TL19009              LAFLEUR,CAROLINE        25-MAY-19
IML-2019-09 Transects PMZA/Releve maquereaux          18TL19009              LAFLEUR,CAROLINE        25-MAY-19
IML-2019-09 Sections du PMZA/Relevé maquereau         18TL19009              LAFLEUR,CAROLINE        25-MAY-19
BCD2019667      18VA19667        PAULEY, KEVIN  09-JAN-19

The best way to approach this is with a lookup table that contains both the cruise name and the cruise descriptor, which can easily be assembled from the mission table in biochem.

**Comment by clayton33** [comment]
My hesitation right now is the fact that the mission descriptor for COR2019001 and COR-2019-002 is the same, 18OL19001, yikes, that's not good. I've asked Diana to point me to someone to ask how the mission descriptor is constructed, so stay tuned. If that leads me nowhere we'll go with using mission table from BIOCHEM.

**Comment by clayton33** [comment]
I came across this document,

https://waves-vagues.dfo-mpo.gc.ca/Library/351319.pdf

in Annex II the construction of mission descriptors is summarized. For more "recent" descriptors , here I'm not sure what recent means, perhaps 1972 to present (?), characters 01-04 use ICES platform codes. I went there, 

https://ocean.ices.dk/codes/ShipCodes.aspx 

and did some searching.

1. I searched `HUDSON` and it gave me as expected, `18HU`
2. I then searched `VIOLA` to see if CCGS Viola M. Davidson is in there, and it returned `18AU`
3. I also searched `SIGMA-T` to see if CCGS Sigma-T was there and it returned, `18SG`

But as outlined in the DFO document, they use `VA` to represent measurements that were taken from a small vessel... so well... I guess I'll waive a white flag. Therefore, @casaultb , can you add a mission descriptor lookup table ? And if my file contains enough data, please merge. If not, please tell me what metadata columns I am missing to best match up our data.

**Comment by casaultb** [comment]
That’s progress. I will pull recent (1999+) records from Biochem and filter the missions relevant to AZMP.

**Comment by Echisholm21** [comment]
Ideas why this build failed? @clayton33 @casaultb

**Comment by clayton33** [comment]
hmNnmnn... no... it built fine when I did my initial pull request but maybe something went sideways when I pulled your fork yesterday, @Echisholm21 ?

**Comment by clayton33** [comment]
I just ran a `check` ... I think this is what's causing it to fail 

```
checking dependencies in R code ... WARNING
  Unexported object imported by a ':::' call: 'tools:::fetchRdDB'
    See the note in ?`:::` about the use of this operator.
    Including base/recommended package(s):
    'tools'
```

**Comment by Echisholm21** [comment]
This could definitely be it. The updated search function doesn't have that chunk anymore so we should be able to get rid of that once I pull request with my branch. Wanted to make sure I wasn't going to compound the issue

**Pull request merged**
