### PR TITLE
Data system update

### PR DESCRIPTION
**Pull request by Echisholm21**
Bug fixes
* data documentation commented out if data frame has not yet been created in data folder
* fixes data update system to work with Benoit and Chantelle's data types
*  removes Mar.utils dependency (fix from Mike!)

Other
* rename files and functions based on underscore convention of data tables
* create sandbox folders for each developer (and add to Rbuildignore)

### CODE REVIEW

**Comment by Echisholm21** [comment]
@clayton33 This should build now without issue 👍

**Comment by clayton33** [comment]
Awesome, look forward to merging these changes into my fork :)

**Comment by clayton33** [comment]
I merged these changes into my fork, and it's still not able to complete a check, this is what I get : 
```
==> devtools::check()

Updating azmpdata documentation
Loading azmpdata

Maritimes/Mar.utils: Latest and greatest version confirmed

casaultb/azmpdata: Latest and greatest version confirmed
Version: 0.2019.0.9000
Writing NAMESPACE
Error: 'chlorophyll_inventory_timeseries_hl2' is not an exported object from 'namespace:azmpdata'
Execution halted

Exited with status 1.
```

**Comment by casaultb** [comment]
Ok, I will have a closer look. This was an old dataset that should no longer be there (along with a couple of others).

**Comment by clayton33** [comment]
@casaultb  I deleted that comment because I accidentally didn't pull on my local machine. so i'm going to delete the comment  you just posted and this one in a few hours so we don't get confused in the future.

**Pull request merged**
