### PR TITLE
Implement website and data updates

### PR DESCRIPTION
**Pull request by Echisholm21**
- Some data updates including new spatial data names for physical and remote sensing data
- pkgdown implementation is prepped (needs to be fully implemented through github)
- update to meeting notes

### CODE REVIEW

**Comment by casaultb** [comment]
@Echisholm21 : check() fails.

E  creating vignettes (15.6s)
   --- re-building 'plotting_azmpdata.Rmd' using rmarkdown
   Quitting from lines 68-120 (plotting_azmpdata.Rmd) 
   Error: processing vignette 'plotting_azmpdata.Rmd' failed with diagnostics:
   could not find function "all_of"
   --- failed re-building 'plotting_azmpdata.Rmd'
   
   --- re-building 'search_azmpdata.Rmd' using rmarkdown
   Quitting from lines 76-77 (search_azmpdata.Rmd) 
   Error: processing vignette 'search_azmpdata.Rmd' failed with diagnostics:
   Can't join on 'variable' x 'variable' because of incompatible types (logical / character)
   --- failed re-building 'search_azmpdata.Rmd'
   
   --- re-building 'style_guide.Rmd' using rmarkdown
   --- finished re-building 'style_guide.Rmd'
   
   --- re-building 'update_azmpdata.Rmd' using rmarkdown
   --- finished re-building 'update_azmpdata.Rmd'
   
   SUMMARY: processing the following files failed:
     'plotting_azmpdata.Rmd' 'search_azmpdata.Rmd'

**Comment by Echisholm21** [comment]
Not sure what is failing because this says all checks passed... is check() on your local machine not passing?

**Comment by Echisholm21** [comment]
The first error should be solved by adding 
library(dplyr)
to the top of plotting_azmpdata.Rmd

The second seems to be a data issue, I would have to see what is happening on your machine to help troubleshoot. I would suggest going through the vignette line by line (running manually) to try to isolate where the issue is.

**Comment by casaultb** [comment]
The second error appears to be from the full_join command in variable_lookup.R because of incompatible types between the two data frames being joined.

**Comment by casaultb** [comment]
Actually, the error appears to occur prior to the full_join:

variable_lookup('nitrate', search_help = TRUE)
Error in names(help_list) <- d : 
  'names' attribute [369] must be the same length as the vector [362]

**Pull request merged**
